# https://kind.sigs.k8s.io/docs/user/configuration/
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  disableDefaultCNI: true
  apiServerPort: 6443
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: "10.96.0.1/12"
    podSubnet: "10.240.0.0/16"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /dev
    containerPath: /dev
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
  extraMounts:
  - hostPath: /dev
    containerPath: /dev
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
# - role: worker
#   extraPortMappings:
#   - containerPort: 80
#     hostPort: 81
#   - containerPort: 443
#     hostPort: 444
#   - containerPort: 2223
#     hostPort: 2223
#   extraMounts:
#   - hostPath: /dev
#     containerPath: /dev
#   - hostPath: /var/run/docker.sock
#     containerPath: /var/run/docker.sock